version: "3"
services:
  api:
    image: node:lts
    command: yarn start:debug
    user: node
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    environment:
      - NODE_ENV=development
    ports:
      - 3000:3000
      - 9229:9229
