version: "3"
services:
  api:
    image: node:alpine
    command: yarn start:debug
    user: node
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
      - /home/node/app/node_modules
    environment:
      - NODE_ENV=development
    ports:
      - 3000:3000
      - 9229:9229
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: auth-example
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: secret
  db_admin:
    image: dpage/pgadmin4
    ports:
      - 8088:80
    environment:
      PGADMIN_DEFAULT_EMAIL: user@docker.net
      PGADMIN_DEFAULT_PASSWORD: secret
    depends_on:
      - db
    logging:
      driver: none
